### ISSUE TITLE
Error installing `geniusweb` package on M1 Mac

### ISSUE THREAD

**Issue by owen-hayes** [brenting/ANL-2023-example-agent#2]
I'm having trouble installing the `geniusweb` package on my Mac. I'm not sure if it's because I have an M1 chip or if it's a problem with all Macs, but a TA in the lab confirmed that others with Macs have had issues installing the packages from `requirements.txt`.

I have tried installing the requirements in a virtual environment (Python 3.9.16) as well as in the provided Docker container based off the `mcr.microsoft.com/vscode/devcontainers/python:0-3.9-bullseye` image. In both cases, if I remove the `geniusweb` package (`https://tracinsy.ewi.tudelft.nl/pubtrac/GeniusWebPython/export/93/geniuswebcore/dist/geniusweb-1.2.1.tar.gz`) and run `pip install -r requirements.txt`, everything installs successfully (but the project can't run of course because it needs the `geniusweb` package). However, when the `geniusweb` package is in the `requirements.txt` file, I get the below error message. It looks like the problem is related to `PyQt5` – maybe there's some compatibility issue?

```
Defaulting to user installation because normal site-packages is not writeable
Collecting https://tracinsy.ewi.tudelft.nl/pubtrac/GeniusWebPython/export/93/geniuswebcore/dist/geniusweb-1.2.1.tar.gz (from -r requirements.txt (line 1))
  Downloading https://tracinsy.ewi.tudelft.nl/pubtrac/GeniusWebPython/export/93/geniuswebcore/dist/geniusweb-1.2.1.tar.gz
     - 91.4 kB 11.3 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: plotly==5.6.0 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (5.6.0)
Requirement already satisfied: kaleido==0.2.1 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.2.1)
Requirement already satisfied: pandas==1.4.1 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.4.1)
Requirement already satisfied: numpy==1.22.3 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.22.3)
Requirement already satisfied: scipy==1.8.0 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.8.0)
Requirement already satisfied: lightgbm==3.3.2 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: scikit-learn==1.0.2 in /home/vscode/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: six in /home/vscode/.local/lib/python3.9/site-packages (from plotly==5.6.0->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/vscode/.local/lib/python3.9/site-packages (from plotly==5.6.0->-r requirements.txt (line 2)) (8.2.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/vscode/.local/lib/python3.9/site-packages (from pandas==1.4.1->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.9/site-packages (from pandas==1.4.1->-r requirements.txt (line 4)) (2023.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (from lightgbm==3.3.2->-r requirements.txt (line 7)) (0.38.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/vscode/.local/lib/python3.9/site-packages (from scikit-learn==1.0.2->-r requirements.txt (line 8)) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /home/vscode/.local/lib/python3.9/site-packages (from scikit-learn==1.0.2->-r requirements.txt (line 8)) (1.2.0)
Collecting pyson@ https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/312/pyson/dist/pyson-1.1.3.tar.gz
  Downloading https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/312/pyson/dist/pyson-1.1.3.tar.gz
     - 11.1 kB 77.8 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
Collecting utilities@ https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/314/utilitiespy/dist/utilities-1.0.5.tar.gz
  Downloading https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/314/utilitiespy/dist/utilities-1.0.5.tar.gz
     - 7.5 kB 42.9 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
Collecting logging@ https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/226/loggingpy/dist/logging-1.0.0.tar.gz
  Downloading https://tracinsy.ewi.tudelft.nl/pubtrac/Utilities/export/226/loggingpy/dist/logging-1.0.0.tar.gz
     - 2.6 kB ? 0:00:00
  Preparing metadata (setup.py) ... done
Collecting websocket-client==1.0.1
  Using cached websocket_client-1.0.1-py2.py3-none-any.whl (68 kB)
Collecting PyQt5==5.15.6
  Using cached PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-_9f9immx/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by brenting** [comment]
It looks like this is indeed an M1 Mac-specific issue. I do not have an M1 Mac so I can't replicate the issue, but maybe this helps:
https://stackoverflow.com/questions/65447314/attributeerror-module-sipbuild-api-has-no-attribute-prepare-metadata-for-bui
